CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE DATABASE iam;
CREATE DATABASE customer;
CREATE DATABASE food;
CREATE DATABASE vendor;
CREATE DATABASE product;
CREATE DATABASE cart;

GRANT ALL PRIVILEGES ON DATABASE iam TO oeuser;
GRANT ALL PRIVILEGES ON DATABASE customer TO oeuser;
GRANT ALL PRIVILEGES ON DATABASE food TO oeuser;
GRANT ALL PRIVILEGES ON DATABASE vendor TO oeuser;
GRANT ALL PRIVILEGES ON DATABASE product TO oeuser;
GRANT ALL PRIVILEGES ON DATABASE cart TO oeuser;