---
servers:
- url: "http://localhost:8080"
openapi: "3.0.0"
paths:
  /foods:
    $ref: "./food.yaml#/paths/~1foods"
  /categories/{id}:
    $ref: "./food.yaml#/paths/~1categories~1{id}"
  /foods/{id}:
    $ref: "./food.yaml#/paths/~1foods~1{id}"
  /categories:
    $ref: "./food.yaml#/paths/~1categories"
info:
  title: "merged spec"
  description: "merged spec"
  version: "1.0.0"
