changeLogFile:src/main/resources/db/changelog-master.yaml
url:jdbc:postgresql://localhost:5432/food
username:oeuser
password:password
liquibaseSchemaName:public
defaultSchemaName:public
outputChangeLogFile:target/db.changelog-diff.xml