services:
  postgres:
    container_name: postgres
    image: postgres:17.5
    hostname: postgres
    environment:
      - 'POSTGRES_DB=oe'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=oeuser'
    ports:
      - '5432:5432'
    volumes:
      - pg_volumeOE:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - oe-network

  keycloak:
    container_name: keycloak
    image: keycloak/keycloak:26.4
    command:
      - start-dev
    #      - --import-realm
    environment:
      KC_HOSTNAME_URL: http://localhost:9080
      KC_HTTP_PORT: 9080
      KC_HOSTNAME_STRICT_BACKCHANNEL: 'false'
      KC_HTTP_ENABLED: 'true'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_HEALTH_ENABLED: 'true'
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/iam
      KC_DB_USERNAME: oeuser
      KC_DB_PASSWORD: password

    ports:
      - 9080:9080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - oe-network
#    volumes:
#      - ./realm-export.json:/opt/keycloak/data/import/realm.json

networks:
  oe-network:
    driver: bridge

volumes:
  pg_volumeOE: