server:
  port: 8080
  name: food


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/food
    username: oeuser
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/realms/oe


springdoc:
  swagger-ui:
    path: /swagger-ui
    show-extensions: true
    show-common-extensions: true
  api-docs:
    path: /v3/api-docs/valami